# Site settings
title: Maxwood Industries Private Limited
email: sales@maxwood.in
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://www.maxwood.in" # the base hostname & protocol for your site

# twitter_username:
# github_username:

# Build settings
markdown: kramdown